/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazUsuario;
import java.util.HashMap;
import modeloBancario.*;
/**
 *
 * @author Daniel
 */
public class InterfazUsuario extends javax.swing.JFrame {
    
    private HashMap<Integer, Cuenta> cuentas = new HashMap<>();
    
    /**
     * Creates new form InterfazUsuario
     */
    public InterfazUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        tipoCuenta = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        direccionTextField = new javax.swing.JTextField();
        telefonoTextField = new javax.swing.JTextField();
        tipoCuentaLabel = new javax.swing.JLabel();
        cuentaCorrienteRadio = new javax.swing.JRadioButton();
        cuentaAhorroRadio = new javax.swing.JRadioButton();
        interesVariableTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        crearClienteBoton = new javax.swing.JButton();
        numeroCuentaTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        saldoTextField = new javax.swing.JTextField();
        saldoInicialLabel = new javax.swing.JLabel();
        saldoMinimoTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        idTextField2 = new javax.swing.JTextField();
        idLabel2 = new javax.swing.JLabel();
        datosClienteBoton = new javax.swing.JButton();
        ingresarTextField = new javax.swing.JTextField();
        ingresarBoton = new javax.swing.JButton();
        retirarTextField = new javax.swing.JTextField();
        retirarBoton = new javax.swing.JButton();
        actualizarSaldoBoton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        desplegable = new javax.swing.JComboBox<>();
        modificarTextField = new javax.swing.JTextField();
        modificarBoton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaTexto = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modelo Bancario");

        idLabel.setText("ID");

        nombreLabel.setText("Nombre");

        direccionLabel.setText("Dirección");

        telefonoLabel.setText("Teléfono");

        idTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTextFieldMouseClicked(evt);
            }
        });
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        nombreTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreTextFieldMouseClicked(evt);
            }
        });

        direccionTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                direccionTextFieldMouseClicked(evt);
            }
        });
        direccionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionTextFieldActionPerformed(evt);
            }
        });

        telefonoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telefonoTextFieldMouseClicked(evt);
            }
        });

        tipoCuentaLabel.setText("Tipo de cuenta:");

        tipoCuenta.add(cuentaCorrienteRadio);
        cuentaCorrienteRadio.setText("Cuenta Corriente");
        cuentaCorrienteRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentaCorrienteRadioMouseClicked(evt);
            }
        });
        cuentaCorrienteRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuentaCorrienteRadioActionPerformed(evt);
            }
        });

        tipoCuenta.add(cuentaAhorroRadio);
        cuentaAhorroRadio.setText("Cuenta Ahorro");
        cuentaAhorroRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuentaAhorroRadioMouseClicked(evt);
            }
        });

        interesVariableTextField.setText("Interés variable a introducir");
        interesVariableTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                interesVariableTextFieldMouseClicked(evt);
            }
        });
        interesVariableTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interesVariableTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de interés fijo: 15%");

        crearClienteBoton.setText("Crear cliente");
        crearClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearClienteBotonActionPerformed(evt);
            }
        });

        numeroCuentaTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                numeroCuentaTextFieldMouseClicked(evt);
            }
        });

        jLabel1.setText("Número de cuenta");

        saldoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saldoTextFieldMouseClicked(evt);
            }
        });

        saldoInicialLabel.setText("Saldo inicial");

        saldoMinimoTextField.setText("Saldo mínimo a introducir");
        saldoMinimoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saldoMinimoTextFieldMouseClicked(evt);
            }
        });
        saldoMinimoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoMinimoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idLabel)
                        .addGap(18, 18, 18)
                        .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(telefonoLabel)
                            .addComponent(direccionLabel)
                            .addComponent(nombreLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTextField)
                            .addComponent(direccionTextField)
                            .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(numeroCuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saldoInicialLabel)
                        .addGap(18, 18, 18)
                        .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(crearClienteBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saldoMinimoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cuentaCorrienteRadio)
                                    .addGap(44, 44, 44)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(tipoCuentaLabel))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cuentaAhorroRadio)
                                    .addGap(47, 47, 47)
                                    .addComponent(interesVariableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(68, 68, 68))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(tipoCuentaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuentaCorrienteRadio)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuentaAhorroRadio)
                    .addComponent(interesVariableTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saldoMinimoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(crearClienteBoton)
                .addGap(15, 15, 15))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccionLabel)
                    .addComponent(direccionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefonoLabel)
                    .addComponent(telefonoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroCuentaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saldoInicialLabel))
                .addContainerGap())
        );

        jTabbedPane2.addTab("Crear cliente", jPanel1);

        idTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextField2ActionPerformed(evt);
            }
        });

        idLabel2.setText("ID");

        datosClienteBoton.setText("Visualizar datos de cliente");
        datosClienteBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datosClienteBotonActionPerformed(evt);
            }
        });

        ingresarTextField.setText("Inserte la cantidad a ingresar");
        ingresarTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarTextFieldMouseClicked(evt);
            }
        });

        ingresarBoton.setText("Ingresar");
        ingresarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBotonActionPerformed(evt);
            }
        });

        retirarTextField.setText("Inserte la cantidad a retirar");
        retirarTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirarTextFieldMouseClicked(evt);
            }
        });
        retirarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarTextFieldActionPerformed(evt);
            }
        });

        retirarBoton.setText("Retirar");
        retirarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarBotonActionPerformed(evt);
            }
        });

        actualizarSaldoBoton.setText("Actualizar saldo");
        actualizarSaldoBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarSaldoBotonActionPerformed(evt);
            }
        });

        jLabel3.setText("Introduzca un ID de cliente y a continuación realice una acción:");

        desplegable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Teléfono", "Dirección", "Número de cuenta", "Saldo mínimo", "Interés variable" }));

        modificarTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarTextFieldActionPerformed(evt);
            }
        });

        modificarBoton.setText("Modificar");
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(desplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(modificarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modificarBoton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ingresarTextField)
                                            .addComponent(retirarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ingresarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(retirarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(41, 41, 41)
                                        .addComponent(actualizarSaldoBoton))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(idLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(idTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(datosClienteBoton)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(219, 219, 219))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel2)
                    .addComponent(idTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datosClienteBoton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarBoton)
                    .addComponent(desplegable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingresarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarBoton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retirarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retirarBoton)
                    .addComponent(actualizarSaldoBoton))
                .addGap(14, 14, 14))
        );

        jTabbedPane2.addTab("Gestionar cliente", jPanel2);

        areaTexto.setEditable(false);
        areaTexto.setColumns(20);
        areaTexto.setRows(5);
        jScrollPane2.setViewportView(areaTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void direccionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_direccionTextFieldActionPerformed

    private void cuentaCorrienteRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuentaCorrienteRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuentaCorrienteRadioActionPerformed

    private void crearClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearClienteBotonActionPerformed
        
        Cliente cliente = new Cliente(
                Integer.parseInt(this.idTextField.getText()),
                this.nombreTextField.getText(),
                this.direccionTextField.getText(),
                this.telefonoTextField.getText()
        );
        Cuenta cuenta = null;
        
        if (this.cuentaCorrienteRadio.isSelected()) {
            cuenta = new CuentaCorriente(
                    Integer.parseInt(this.numeroCuentaTextField.getText()),
                    Double.parseDouble(this.saldoTextField.getText()),
                    cliente
            );
        } else if(this.cuentaAhorroRadio.isSelected() && Double.parseDouble(this.saldoTextField.getText()) >= Double.parseDouble(this.saldoMinimoTextField.getText())) {
            cuenta = new CuentaAhorro(Double.parseDouble(
                    this.interesVariableTextField.getText()),
                    Double.parseDouble(this.saldoMinimoTextField.getText()),
                    Integer.parseInt(this.numeroCuentaTextField.getText()),
                    Double.parseDouble(this.saldoTextField.getText()),
                    cliente
            );
        }
        
        if (cuenta != null) {
            cuentas.put(cliente.getIdCliente(), cuenta);
            this.areaTexto.setText("Nuevo cliente creado.");
        } else {
            this.areaTexto.setText("No se ha creado la cuenta");
        }
    }//GEN-LAST:event_crearClienteBotonActionPerformed

    private void idTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextField2ActionPerformed

    private void datosClienteBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datosClienteBotonActionPerformed
        Cuenta aux = cuentas.get(Integer.parseInt(this.idTextField2.getText()));
        if (aux instanceof CuentaCorriente) {
            this.areaTexto.setText(
                    "CUENTA CORRIENTE" + "\n" +
                    "==================" + "\n" + "\n" +
                    "ID de cliente: " + String.format("%08d", aux.getTitular().getIdCliente()) + "\n" +
                    "Nombre cliente: " + aux.getTitular().getNombre() + "\n" +
                    "Dirección: " + aux.getTitular().getDireccion() + "\n" +
                    "Telefono: " + aux.getTitular().getTelefono() + "\n" +
                    "Número de cuenta: " + String.format("%08d",aux.getNumeroDeCuenta()) + "\n" +
                    "Saldo disponible: " + aux.getSaldo() + " € \n" +
                    "Interés fijo: " + ((CuentaCorriente) aux).getInteresFijo() * 100 + "%"
            );
        } else if (aux instanceof CuentaAhorro) {
            this.areaTexto.setText(
                    "CUENTA AHORRO" + "\n" +
                    "===============" + "\n" + "\n" +
                    "ID de cliente: " + String.format("%08d", aux.getTitular().getIdCliente()) + "\n" +
                    "Nombre cliente: " + aux.getTitular().getNombre() + "\n" +
                    "Dirección: " + aux.getTitular().getDireccion() + "\n" +
                    "Telefono: " + aux.getTitular().getTelefono() + "\n" +
                    "Número de cuenta: " + String.format("%08d", aux.getNumeroDeCuenta()) + "\n" +
                    "Saldo disponible: " + aux.getSaldo() + " € \n" +
                    "Saldo mínimo; " + ((CuentaAhorro) aux).getSaldoMinimo() + " € \n" +
                    "Interés variable: " + ((CuentaAhorro) aux).getInteresVariable() * 100 + "%"
            );
        }
    }//GEN-LAST:event_datosClienteBotonActionPerformed

    private void saldoMinimoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoMinimoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoMinimoTextFieldActionPerformed

    private void ingresarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBotonActionPerformed
        Cuenta aux = cuentas.get(Integer.parseInt(this.idTextField2.getText()));
        this.areaTexto.setText(aux.ingresar(Integer.parseInt(this.ingresarTextField.getText())));
    }//GEN-LAST:event_ingresarBotonActionPerformed

    private void retirarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarTextFieldActionPerformed
        Cuenta aux = cuentas.get(Integer.parseInt(this.idTextField2.getText()));
        aux.ingresar(Integer.parseInt(this.retirarTextField.getText()));
    }//GEN-LAST:event_retirarTextFieldActionPerformed

    private void ingresarTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarTextFieldMouseClicked
        this.ingresarTextField.setText("");
    }//GEN-LAST:event_ingresarTextFieldMouseClicked

    private void retirarTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirarTextFieldMouseClicked
        this.retirarTextField.setText("");
    }//GEN-LAST:event_retirarTextFieldMouseClicked

    private void interesVariableTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interesVariableTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_interesVariableTextFieldActionPerformed

    private void interesVariableTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_interesVariableTextFieldMouseClicked
        this.interesVariableTextField.setText("");
    }//GEN-LAST:event_interesVariableTextFieldMouseClicked

    private void saldoMinimoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saldoMinimoTextFieldMouseClicked
        this.saldoMinimoTextField.setText("");
    }//GEN-LAST:event_saldoMinimoTextFieldMouseClicked

    private void actualizarSaldoBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarSaldoBotonActionPerformed
        Cuenta aux = cuentas.get(Integer.parseInt(this.idTextField2.getText()));
        this.areaTexto.setText(aux.actualizarSaldo());
    }//GEN-LAST:event_actualizarSaldoBotonActionPerformed

    private void retirarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarBotonActionPerformed
        Cuenta aux = cuentas.get(Integer.parseInt(this.idTextField2.getText()));
        this.areaTexto.setText(aux.retirar(Integer.parseInt(this.retirarTextField.getText())));
    }//GEN-LAST:event_retirarBotonActionPerformed

    private void idTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTextFieldMouseClicked
        this.idTextField.setText("");
        
    }//GEN-LAST:event_idTextFieldMouseClicked

    private void nombreTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreTextFieldMouseClicked
        this.nombreTextField.setText("");
        
    }//GEN-LAST:event_nombreTextFieldMouseClicked

    private void direccionTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_direccionTextFieldMouseClicked
        this.direccionTextField.setText("");
        
    }//GEN-LAST:event_direccionTextFieldMouseClicked

    private void telefonoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telefonoTextFieldMouseClicked
       this.telefonoTextField.setText("");
    }//GEN-LAST:event_telefonoTextFieldMouseClicked

    private void numeroCuentaTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numeroCuentaTextFieldMouseClicked
        this.numeroCuentaTextField.setText("");
        
    }//GEN-LAST:event_numeroCuentaTextFieldMouseClicked

    private void saldoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saldoTextFieldMouseClicked
        this.saldoTextField.setText("");
    }//GEN-LAST:event_saldoTextFieldMouseClicked
    
    private void cuentaCorrienteRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentaCorrienteRadioMouseClicked
        this.interesVariableTextField.setEnabled(false);
        this.saldoMinimoTextField.setEnabled(false);
    }//GEN-LAST:event_cuentaCorrienteRadioMouseClicked

    private void cuentaAhorroRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuentaAhorroRadioMouseClicked
        this.interesVariableTextField.setEnabled(true);
        this.saldoMinimoTextField.setEnabled(true);
    }//GEN-LAST:event_cuentaAhorroRadioMouseClicked

    private void modificarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarTextFieldActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        Cuenta aux = cuentas.get(Integer.parseInt(this.idTextField2.getText()));
        if (this.desplegable.getSelectedItem() == "Nombre") {
            aux.getTitular().setNombre(this.modificarTextField.getText());
            this.areaTexto.setText("Nombre modificado");
        } else if (this.desplegable.getSelectedItem() == "Teléfono") {
            aux.getTitular().setTelefono(this.modificarTextField.getText());
            this.areaTexto.setText("Teléfono modificado");
        } else if (this.desplegable.getSelectedItem() == "Dirección") {
            aux.getTitular().setDireccion(this.modificarTextField.getText());
            this.areaTexto.setText("Dirección modificada");
        } else if (this.desplegable.getSelectedItem() == "Número de cuenta") {
            aux.setNumeroDeCuenta(Integer.parseInt(this.modificarTextField.getText()));
            this.areaTexto.setText("Número de cuenta modificado");
        } else if (this.desplegable.getSelectedItem() == "Saldo mínimo") {
            ((CuentaAhorro) aux).setSaldoMinimo(Double.parseDouble(this.modificarTextField.getText()));
            this.areaTexto.setText("Saldo mínimo modificado");
        } else if (this.desplegable.getSelectedItem() == "Interés variable") {
            ((CuentaAhorro) aux).setInteresVariable(Integer.parseInt(this.modificarTextField.getText()));
            this.areaTexto.setText("Interés variable modificado");
        }
    }//GEN-LAST:event_modificarBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarSaldoBoton;
    private javax.swing.JTextArea areaTexto;
    private javax.swing.JButton crearClienteBoton;
    private javax.swing.JRadioButton cuentaAhorroRadio;
    private javax.swing.JRadioButton cuentaCorrienteRadio;
    private javax.swing.JButton datosClienteBoton;
    private javax.swing.JComboBox<String> desplegable;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextField direccionTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JTextField idTextField;
    private javax.swing.JTextField idTextField2;
    private javax.swing.JButton ingresarBoton;
    private javax.swing.JTextField ingresarTextField;
    private javax.swing.JTextField interesVariableTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JTextField modificarTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField numeroCuentaTextField;
    private javax.swing.JButton retirarBoton;
    private javax.swing.JTextField retirarTextField;
    private javax.swing.JLabel saldoInicialLabel;
    private javax.swing.JTextField saldoMinimoTextField;
    private javax.swing.JTextField saldoTextField;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JTextField telefonoTextField;
    private javax.swing.ButtonGroup tipoCuenta;
    private javax.swing.JLabel tipoCuentaLabel;
    // End of variables declaration//GEN-END:variables
}
